spring:
  application:
    name: new-mcp-client
  ai:
    bedrock:
      aws:
        region: us-east-1
      converse:
        chat:
          options:
            model: us.anthropic.claude-sonnet-4-20250514-v1:0
    mcp:
      client:
        toolcallback:
          enabled: true
        type: sync
        streamable-http:
          connections:
            server1:
              url: http://localhost:50003
        name: new-mcp-client
  security:
    oauth2:
      client:
        provider:
          authserver:
            issuer-uri: ${ISSUER_URL}
        registration:
          mcp-client-credentials:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            provider: authserver
  client-credentials:
    audience: ${AUDIENCE}
server:
  port: 50004
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: TRACE